# Generated by Django 5.0.4 on 2024-05-05 19:29

import naoka.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mappings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mappings", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                            ("visual_novel", "Visual Novel"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "title_ro",
                    models.TextField(
                        blank=True, null=True, verbose_name="Title (Romaji)"
                    ),
                ),
                (
                    "title_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Title (Spanish)"
                    ),
                ),
                (
                    "title_na",
                    models.TextField(
                        blank=True, null=True, verbose_name="Title (Native)"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_large", models.URLField(blank=True, null=True)),
                ("image_small", models.URLField(blank=True, null=True)),
                ("banner", models.URLField(blank=True, null=True)),
                ("episodes", models.PositiveIntegerField(blank=True, null=True)),
                ("chapters", models.PositiveIntegerField(blank=True, null=True)),
                ("volumes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration",
                    models.TimeField(
                        blank=True,
                        help_text="The average duration of each episode.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("hiatus", "Hiatus"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="auto",
                        max_length=9,
                    ),
                ),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="Start date"),
                ),
                (
                    "date_finish",
                    models.DateField(blank=True, null=True, verbose_name="Date finish"),
                ),
                ("genres", models.JSONField()),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tv", "Tv"),
                            ("tv_short", "Tv Short"),
                            ("movie", "Movie"),
                            ("special", "Special"),
                            ("ova", "Ova"),
                            ("ona", "Ona"),
                            ("music", "Music"),
                            ("manga", "Manga"),
                            ("novel", "Novel"),
                            ("light_novel", "Light Novel"),
                            ("one_shot", "One Shot"),
                            ("doujinshi", "Doujinshi"),
                            ("manhwa", "Manhwa"),
                            ("manhua", "Manhua"),
                            ("oel", "Oel"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "G"),
                            ("pg", "Pg"),
                            ("pg_13", "Pg 13"),
                            ("r", "R"),
                            ("r_plus", "R Plus"),
                            ("rx", "Rx"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("is_adult", models.BooleanField(default=False)),
                ("links", models.JSONField()),
                (
                    "mapping",
                    models.CharField(
                        db_index=True,
                        help_text="Format: MediaType:Provider:ID",
                        max_length=32,
                        validators=[naoka.media.models.validate_mapping],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
