# Generated by Django 5.0.4 on 2024-05-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Title (English)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Title (Spanish)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_na",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Title (Native)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_ro",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Title (Romaji)"
            ),
        ),
    ]
