# Generated by Django 5.0.4 on 2024-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_media_title_en_alter_media_title_es_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mappings",
            name="mappings",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="media",
            name="genres",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="media",
            name="links",
            field=models.JSONField(default=list),
        ),
    ]
