# Generated by Django 5.0.4 on 2024-05-06 18:31

import naoka.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_alter_mappings_mappings_alter_media_genres_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"verbose_name_plural": "Media"},
        ),
        migrations.RemoveField(
            model_name="media",
            name="id",
        ),
        migrations.AlterField(
            model_name="media",
            name="mapping",
            field=models.CharField(
                help_text="Format: MediaType:Provider:ID",
                max_length=32,
                primary_key=True,
                serialize=False,
                validators=[naoka.media.models.validate_mapping],
            ),
        ),
    ]
