# Generated by Django 5.0.4 on 2024-05-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_alter_media_is_adult_alter_media_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="media",
            name="is_adult",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=198, null=True, verbose_name="Title (English)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=198, null=True, verbose_name="Title (Spanish)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_na",
            field=models.CharField(
                blank=True, max_length=198, null=True, verbose_name="Title (Native)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_ro",
            field=models.CharField(
                blank=True, max_length=198, null=True, verbose_name="Title (Romaji)"
            ),
        ),
    ]
