# Generated by Django 5.0.4 on 2024-05-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0006_alter_media_genres_alter_media_is_adult_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="date_finish",
            field=models.DateField(blank=True, null=True, verbose_name="Finish date"),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Title (English)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Title (Spanish)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_na",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Title (Native)"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title_ro",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Title (Romaji)"
            ),
        ),
    ]
