changelog:
  categories:
    - title: Updates
      labels:
        - enhancement
    - title: Providers
      labels:
        - provider
      exclude:
        labels:
          - enhancements
    - title: Other Changes
      labels:
        - "*"
