# Generated by Django 4.2.7 on 2023-11-16 04:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.TextField(null=True)),
                ('name_middle', models.TextField(null=True)),
                ('name_last', models.TextField(null=True)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=2), blank=True, help_text='An array of arrays containing two items each, being the first one the language code and the second one the description for that language.', size=None)),
                ('image_small', models.URLField(null=True)),
                ('image_medium', models.URLField(null=True)),
                ('image_large', models.URLField(null=True)),
                ('mappings', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main'), ('supporting', 'Supporting')], default='main', max_length=10)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='characters.character')),
            ],
        ),
    ]
